-- farm2.0 Seed Data (PostgreSQL Version)

-- Initial Configuration
INSERT INTO fazenda_config (chave, valor, descricao) VALUES
('game_version', 'V.2.0.1', 'Versão atual do jogo'),
('energy_restore_per_hour', '5', 'Energia recuperada por hora'),
('crow_chance_percent', '10', 'Chance de aparecimento de corvos'),
('pest_chance_percent', '20', 'Chance de aparecimento de pragas'),
('global_discount', '0', 'Desconto global na loja (%)'),
('world_tree_active_users_last_week', '1', 'Usuários ativos na semana anterior (padrão 1)'),
('slot_price_base', '500', 'Preço base para comprar novos terrenos')
ON CONFLICT (chave) DO NOTHING;

-- Items and Crops
INSERT INTO fazenda_itens_config (item_id, tipo, label, price_coins, price_diamonds, reward_base, grow_hours) VALUES
('vasoPequeno', 'item', 'Pote Pequeno', 20, 0, 0, 0),
('vasoGrande', 'item', 'Pote Grande', 40, 0, 0, 0),
('agua', 'item', 'Água', 10, 0, 0, 0),
('pesticida', 'item', 'Pesticida', 35, 0, 0, 0),
('espantalho', 'item', 'Espantalho', 0, 500, 0, 0),
('flor_01_rosa_adulta', 'flower', 'Rosa', 100, 0, 150, 0.03),
('flor_02_girassol_adulta', 'flower', 'Girassol', 100, 0, 150, 0.03),
('flor_03_roxa_adulta', 'flower', 'Roxa', 100, 0, 150, 0.03),
('flor_04_azul_adulta', 'flower', 'Azul', 100, 0, 150, 0.03),
('flor_05_laranja_adulta', 'flower', 'Laranja', 100, 0, 150, 0.03),
('flor_06_branca_adulta', 'flower', 'Branca', 100, 0, 150, 0.03),
('flor_07_vermelha_adulta', 'flower', 'Vermelha', 100, 0, 150, 0.03),
('flor_08_violeta_adulta', 'flower', 'Violeta', 100, 0, 150, 0.03),
('flor_09_lilas_adulta', 'flower', 'Lilás', 100, 0, 150, 0.03),
('flor_10_teal_adulta', 'flower', 'Teal', 100, 0, 150, 0.03),
('arvore_01_frutifera_adulta', 'tree', 'Árvore Frutífera', 250, 0, 438, 0.08),
('arvore_02_copa_adulta', 'tree', 'Árvore Copa', 250, 0, 438, 0.08),
('arvore_03_ornamental_adulta', 'tree', 'Árvore Ornamental', 250, 0, 438, 0.08),
('arvore_04_volumosa_adulta', 'tree', 'Árvore Volumosa', 250, 0, 438, 0.08),
('arvore_05_alta_adulta', 'tree', 'Árvore Alta', 250, 0, 438, 0.08)
ON CONFLICT (item_id) DO NOTHING;

-- Mission Templates
INSERT INTO fazenda_missoes_template (label, tipo, target, reward_type, reward_amount, weight) VALUES
('Plante 2 flores', 'plant_flowers', 2, 'coins', 120, 10),
('Plante 1 árvore', 'plant_trees', 1, 'coins', 180, 10),
('Regue 3 slots', 'water_slots', 3, 'energia', 8, 10),
('Compre 1 terreno', 'unlock_slot', 1, 'coins', 250, 5),
('Colete 400 ouro', 'harvest_gold', 400, 'diamante', 20, 8),
('Remova 1 corvo', 'remove_crow', 1, 'coins', 140, 10),
('Use pesticida 1 vez', 'use_pesticide', 1, 'coins', 120, 10),
('Colha 3 plantas', 'harvest_count', 3, 'coins', 220, 10),
('Doe 100 ouro para a Árvore Mundial', 'donate_tree', 100, 'energia', 5, 10),
('Plante 5 flores', 'plant_flowers', 5, 'coins', 350, 5),
('Regue 10 slots', 'water_slots', 10, 'energia', 25, 5),
('Remova 5 corvos', 'remove_crow', 5, 'diamante', 50, 3),
('Colete 1000 ouro', 'harvest_gold', 1000, 'diamante', 50, 4),
('Colha 10 plantas', 'harvest_count', 10, 'coins', 800, 4),
('Use 5 pesticidas', 'use_pesticide', 5, 'coins', 500, 5),
('Doe para a árvore 3 vezes', 'donate_tree_count', 3, 'diamante', 15, 7),
('Plante 2 árvores', 'plant_trees', 2, 'coins', 400, 5),
('Mantenha o espantalho ativo', 'scarecrow_active', 1, 'coins', 100, 10),
('Compre 5 itens na loja', 'buy_shop', 5, 'energia', 15, 8),
('Gaste 500 ouro', 'spend_gold', 500, 'energia', 10, 10),
('Gaste 50 diamantes', 'spend_diamonds', 50, 'coins', 1000, 2),
('Regue a Árvore Mundial', 'water_world_tree', 1, 'coins', 50, 10),
('Complete 3 missões', 'complete_missions', 3, 'diamante', 30, 2),
('Plante Rosa e Girassol', 'plant_specific_flower', 2, 'coins', 300, 5),
('Tenha 5 slots ativos', 'active_slots', 5, 'coins', 500, 3),
('Colete recompensa da Árvore Mundial', 'collect_tree_reward', 1, 'diamante', 10, 5),
('Plante uma Árvore Frutífera', 'plant_specific_tree', 1, 'coins', 200, 7),
('Use 2 potes grandes', 'use_big_pot', 2, 'coins', 150, 8),
('Use 5 potes pequenos', 'use_small_pot', 5, 'coins', 150, 8),
('Fique online por 1 hora', 'online_time', 60, 'energia', 20, 5),
('Colha uma planta jovem', 'harvest_young', 1, 'coins', 50, 5),
('Use 3 águas em um único slot', 'water_triple', 1, 'coins', 80, 6),
('Remova uma praga rapidamente', 'fast_pest_removal', 1, 'coins', 100, 7),
('Economize 2000 ouro', 'save_gold', 2000, 'diamante', 25, 4),
('Compre um item de diamante', 'buy_diamond_item', 1, 'energia', 50, 2),
('Ajude 5 vizinhos (placeholder)', 'help_neighbors', 5, 'coins', 300, 1),
('Plante 10 sementes', 'plant_seeds', 10, 'coins', 400, 6),
('Regue em 4 períodos diferentes', 'water_periods', 4, 'diamante', 40, 3),
('Doe 500 ouro para a Árvore', 'donate_tree', 500, 'diamante', 10, 5),
('Tenha 2 espantalhos', 'scarecrow_count', 2, 'coins', 300, 3),
('Colha todas as flores do campo', 'harvest_all_flowers', 1, 'coins', 600, 3),
('Plante apenas árvores', 'only_trees', 3, 'coins', 500, 2),
('Use 10 pesticidas no dia', 'pesticide_daily', 10, 'diamante', 60, 2),
('Espante 3 corvos seguidos', 'crows_streak', 3, 'coins', 250, 4),
('Colete 100 ouro de uma vez', 'large_harvest', 1, 'energia', 5, 8),
('Doe energia para a árvore', 'donate_energy', 10, 'coins', 500, 5),
('Compre 2 terrenos novos', 'unlock_slots', 2, 'diamante', 100, 1),
('Complete a meta diária da árvore', 'complete_tree_daily', 1, 'diamante', 50, 1),
('Regue o jardim de manhã', 'morning_water', 3, 'coins', 100, 5),
('Colha à noite', 'night_harvest', 3, 'coins', 100, 5),
('Use o Pote Grande na Flor', 'weird_planting', 1, 'coins', 50, 5);
